"""create profiles table

Revision ID: 00c33382073e
Revises: 14502216bb97
Create Date: 2024-09-21 22:21:03.024312

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.sql import func
# revision identifiers, used by Alembic.
revision = '00c33382073e'
down_revision = '14502216bb97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('subscription_status', mysql.ENUM('ACTIVE', 'INACTIVE'), nullable=False),
    sa.Column('isAdult', sa.Boolean(), nullable=False),
    sa.Column('current_education_level', sa.String(length=120), nullable=False),
    sa.Column('school_name', sa.String(length=120), nullable=True),
    sa.Column('expected_graduation_year', sa.String(length=4), nullable=True),
    sa.Column('desired_course', sa.String(length=120), nullable=True),
    sa.Column('university_choices', sa.JSON(), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('postal_code', sa.String(length=60), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('parent_first_name', sa.String(length=120), nullable=True),
    sa.Column('parent_last_name', sa.String(length=120), nullable=True),
    sa.Column('parent_email', sa.String(length=120), nullable=True),
    sa.Column('parent_phone_number', sa.String(length=15), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=func.now()))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=func.now()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    op.drop_table('profiles')
    # ### end Alembic commands ###
