"""empty message

Revision ID: 44039c75f336
Revises: fcbc5a94a720
Create Date: 2024-09-27 21:14:39.721205

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '44039c75f336'
down_revision = 'fcbc5a94a720'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.alter_column('subscription_status',
               existing_type=mysql.ENUM('ACTIVE', 'INACTIVE'),
               nullable=True)
        batch_op.alter_column('isAdult',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.alter_column('current_education_level',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.alter_column('current_education_level',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('isAdult',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
        batch_op.alter_column('subscription_status',
               existing_type=mysql.ENUM('ACTIVE', 'INACTIVE'),
               nullable=False)

    # ### end Alembic commands ###
