"""empty message

Revision ID: 7db474cb9056
Revises: 8b8b98a665bd
Create Date: 2024-09-28 16:24:01.070756

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7db474cb9056'
down_revision = '8b8b98a665bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passage', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('question', sa.Text(), nullable=False))
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', mysql.TEXT(), nullable=False))
        batch_op.drop_column('question')
        batch_op.drop_column('passage')

    # ### end Alembic commands ###
