"""change column user_id to profile_id in user_questions_history table

Revision ID: 9e2566eeb5dc
Revises: 7a4354c024cc
Create Date: 2024-10-03 10:41:56.703163

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e2566eeb5dc'
down_revision = '7a4354c024cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_questions_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('user_questions_history_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'profiles', ['profile_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_questions_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_questions_history_ibfk_2', 'users', ['user_id'], ['id'])
        batch_op.drop_column('profile_id')

    # ### end Alembic commands ###
