name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > /tmp/ssh_key
          chmod 600 /tmp/ssh_key

      - name: SSH and Deploy
        env:
          AWS_HOST: ${{ secrets.AWS_HOST }}
        run: |
          ssh -o StrictHostKeyChecking=no -i /tmp/ssh_key ubuntu@$AWS_HOST << 'EOF'
            cd scholafit-application
            git pull origin main
            docker-compose up -d --build
          EOF
